env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - google
  - "plugin:react-hooks/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - "react-hooks"
rules:
  no-unused-vars: "off"
  no-prototype-builtins: "off"
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "error"
  react/jsx-uses-react: "error"
  react/jsx-uses-vars: "error"
  no-undef: "off"
#  object-curly-spacing: ["error", "always"]
  react/prop-types: 0
  max-len: ["error", { "code": 240 }]
